### ISSUE TITLE
NavigateToAsync to //Page causes crasch

### ISSUE THREAD

**Issue by KeylinxTobias** [TinyStuff/TinyMvvm#26] opened 2020-11-17 17:59 UTC
Using the default project created in xamarin forms with shell. When doing such things as going from LoginPage to AboutPage using:
await Navigation.NavigateToAsync("//AboutPage");

causes app to crasch with this info:
Global routes currently cannot be the only page on the stack, so absolute routing to global routes is not supported. For now, just navigate to: AboutPage

When using await Navigation.NavigateToAsync("AboutPage"); it works but a back button appears which backs to LoginPage again and that one I don't want to have, since I want to switch to a different navigation stack.

**Comment by dhindrik** [comment] 2020-11-18 07:44
Are you using the ShellNavigationHelper?

Will it work with Shell.Current.GoToAsync, because NavigateToAsync is only wrapping that method if you are using ShellNavigationHelper. 

It sounds like a Shell related issue. But I will take a look and see if I can find any problem with TinyMvvm.

**Comment by KeylinxTobias** [comment] 2020-11-18 07:49
Tried both and none of them worked. When not using TinyMvvm the navigation worked as it should. I think the issue here is that the LoginPage is supposed to not have the flyout and be part of the bottom tabs so it is a little bit different. Sorry for my fussy description here, been playing around with Shell for the first time :)

**Comment by dhindrik** [comment] 2020-11-20 09:45
Do you have a project that you can share that reproduces it?

**Comment by KeylinxTobias** [comment] 2020-11-20 09:58
Yes I will get back to you with a link to that. I am using Android if that is any better clue to this.

**Comment by KeylinxTobias** [comment] 2020-11-20 15:30
https://github.com/KeylinxTobias/TestTinyMvvmAndShell this is basically the default flyout based example project of Xamarin forms. Upgraded to latest forms and added TinyMvvm.Forms and Autofac Resolver for TinyMvvm. Altered the LoginPage, so if you click on the "logout" option in the flyout the app will crash.

**Comment by dhindrik** [comment] 2020-11-29 23:23
I can not see that this is a TinyMvvm issue. It crashes even without navigating with TinyMvvm. It is probably related to Shell.

If you remove // from the URL it will work. 

```
System.Exception: Global routes currently cannot be the only page on the stack, so absolute routing to global routes is not supported. For now, just navigate to: AboutPage
  at Xamarin.Forms.ShellUriHandler.GenerateRoutePaths (Xamarin.Forms.Shell shell, System.Uri request, System.Uri originalRequest, System.Boolean enableRelativeShellRoutes) [0x000e3] in D:\a\1\s\Xamarin.Forms.Core\Shell\ShellUriHandler.cs:181
  at Xamarin.Forms.ShellUriHandler.GetNavigationRequest (Xamarin.Forms.Shell shell, System.Uri uri, System.Boolean enableRelativeShellRoutes, System.Boolean throwNavigationErrorAsException) [0x0004b] in D:\a\1\s\Xamarin.Forms.Core\Shell\ShellUriHandler.cs:96
  at Xamarin.Forms.Shell.GoToAsync (Xamarin.Forms.ShellNavigationState state, System.Nullable`1[T] animate, System.Boolean enableRelativeShellRoutes) [0x00079] in D:\a\1\s\Xamarin.Forms.Core\Shell\Shell.cs:495
```

Maybe the sample is not up to date. I will close the issue for now, if you have more information you are welcome and submit it and we can reopen it if the new information indicates that it is a TinyMvvm problem.

**Comment by KeylinxTobias** [comment] 2020-11-30 10:10
Maybe I was a little unclear here. The example code I sent is of course working without TinyMvvm, its the default template from Xamarin.

You know what the "//" part of the url means, right? You cannot just simply remove that if you want a new navigation root, it will only push a new view into the stack then.

I manage to get **Shell** navigation to work with TinyMvmm by removing the navigation helpers parts in App.xaml.cs. If thats not related to TinyMvmm I dont know, it can be an Autofac issue as well. For me its a non-issue right now since I did a work around, so it's fine for me that you close this. But if I were the product owner of this framework, I would dig deeper into this.

Best Regards,
Tobias

**Comment by dhindrik** [comment] 2020-11-30 10:23
I will investigate further. I can see now what you mean. It is related to RegisterViewsInAssembly.

Thank you for reporting nd giving me more information :)

**Comment by dhindrik** [comment] 2020-11-30 10:33
The problem occurs when you have a Route that is the same as the name of the class/file. In this case, both the Page and the Route is named LoginPage. I will continue to investigate why that is a problem.

**Comment by KeylinxTobias** [comment] 2020-11-30 10:45
> The problem occurs when you have a Route that is the same as the name of the class/file. In this case, both the Page and the Route is named LoginPage. I will continue to investigate why that is a problem.

Yes I was looking into that aswell since the documentation was stating that you shouldnt do that, but the test project worked fine. A little bit confusing. Let me know if I can assist further.

**Comment by dhindrik** [comment] 2020-12-01 08:56
I rewrote how routes are registered to 3.0, https://github.com/TinyStuff/TinyMvvm/commit/e483799af1ce573f2cb28b4be7144ccd5c03ed93

It will no longer register all views as a route and to use ViewModel Navigation, you need to call InitViewModelNavigation.

I will release it with a pre-3 of 3.0.

**Closed as completed by dhindrik** 2020-12-01 08:56 UTC
Labels: bug
